---
- hosts: remote_server

  tasks:
  - name: unarchive all files
    unarchive:
      src: "{{ item }}"
      dest: "{{ project_root }}"
    with_fileglob:
      - ~/recruiting-system/*.tar.gz

  - name: run docker-compose up -d
    shell: docker-compose up -d
    args:
      chdir: "{{ project_root }}assembly"

  - name: gradle migrate for paper-api
    shell: ./gradlew flywaymigrate
    args:
      chdir: "{{ project_root }}paper-api"
    notify:
      - restart paper-api

  - name: restore jenkins configration
    shell: docker exec -d assembly_jenkins-dind_1 sh -c " rm -rf /var/jenkins_home/jobs/{{ item.name }}; mkdir /var/jenkins_home/jobs/{{ item.name }}; "
          && docker cp "{{ project_root }}assembly/jenkins/{{ item.name }}/config.xml" "assembly_jenkins-dind_1:/var/jenkins_home/jobs/{{ item.name }}"
    with_items:
      - { name: ADD_HOMEWORK }
      - { name: ADD_IMAGE }
      - { name: HOMEWORK_SCORING }
    tags:
      - restore

  - name: restore jenkins plugins
    shell: docker cp {{ item }} "assembly_jenkins-dind_1:/var/jenkins_home/plugins/"
    with_fileglob:
      - "{{ project_root }}assembly/jenkins/plugins/*.hpi"
    notify:
    - restart jenkins-dind

  handlers:
    - name: restart paper-api
      shell: docker restart assembly_paper-api_1
    - name: restart jenkins-dind
      shell: docker restart jenkins-dind