---
- hosts: remote_server

  tasks:
  - name: delete node_modules
    file:
      path: "{{ project_root }}web-api/node_modules"
      state: absent
    become: true
    tags:
      - rm

  - name: copy
    copy:
      src: "{{ item }}"
      dest: "{{ project_root }}"
    with_fileglob:
      - ~/recruiting-system/*.7z

  - name: unzip
    shell: 7z x {{ item }} ./
    with_fileglob:
      - "{{ project_root }}*.7z"

  # - name: unarchive all files
  #   unarchive:
  #     src: "{{ item }}"
  #     dest: "{{ project_root }}"
  #   with_fileglob:
  #     - ~/recruiting-system/*.tar.gz

  - name: run docker-compose up -d
    shell: docker-compose up -d
    args:
      chdir: "{{ project_root }}assembly"

  - name: gradle migrate for paper-api
    shell: ./gradlew flywaymigrate
    args:
      chdir: "{{ project_root }}paper-api"
    notify:
      - restart paper-api

  - name: restore jenkins configration
    shell: docker exec -d assembly_jenkins-dind_1 sh -c " rm -rf /var/jenkins_home/jobs/{{ item.name }}; mkdir /var/jenkins_home/jobs/{{ item.name }}; "
          && docker cp "{{ project_root }}assembly/jenkins/{{ item.name }}/config.xml" "assembly_jenkins-dind_1:/var/jenkins_home/jobs/{{ item.name }}"
    with_items:
      - { name: ADD_HOMEWORK }
      - { name: ADD_IMAGE }
      - { name: HOMEWORK_SCORING }
    tags:
      - config

  - name: restore jenkins plugins
    shell: docker cp "{{ project_root }}assembly/jenkins/plugins/{{ item }}" "assembly_jenkins-dind_1:/var/jenkins_home/plugins/"
    with_items:
      - envinject.hpi
      - git.hpi
      - postbuildscript.hpi
      - structs.hpi
      - workflow-step-api.hpi
      - flexible-publish.hpi
      - junit.hpi
      - run-condition.hpi
      - token-macro.hpi
      - git-client.hpi
      - matrix-project.hpi
      - scm-api.hpi
      - workflow-scm-step.hpi
    notify:
    - restart jenkins-dind
    tags:
      - restore

  - name: restart web-api 
    shell: docker restart assembly_web-api_1

  handlers:
    - name: restart paper-api
      shell: docker restart assembly_paper-api_1
    - name: restart jenkins-dind
      shell: docker restart assembly_jenkins-dind_1
